# Generated by Django 4.2.1 on 2023-05-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio del plan'),
        ),
    ]
