# Generated by Django 4.2.2 on 2023-06-15 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.sucursal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.tipousuario'),
        ),
    ]
