# Generated by Django 4.2.1 on 2023-05-26 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporteprofesor',
            name='deporte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.deporte'),
        ),
        migrations.AlterField(
            model_name='deporteprofesor',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.profesor'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.sucursal'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.tipofuncionario'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.IntegerField(default=1, verbose_name='Precio del plan'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.sucursal'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.tipoprofesor'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='equipamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.equipamiento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='socio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.socio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.plan'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.sucursal'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.tipousuario'),
        ),
    ]
