# Generated by Django 4.2.2 on 2023-06-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_socio_sucursal_alter_usuario_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoreserva',
            name='curso',
        ),
    ]
