# Generated by Django 4.2.1 on 2023-05-12 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_plan_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='socio',
            name='sucursal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.sucursal'),
        ),
    ]
