# Generated by Django 4.2.2 on 2023-06-23 05:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_remove_cursoreserva_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canchasreserva',
            name='reserva',
        ),
        migrations.AddField(
            model_name='cancha',
            name='fechaCancha',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 5, 31, 44, 359512, tzinfo=datetime.timezone.utc), verbose_name='Fecha de la Reserva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancha',
            name='horaCancha',
            field=models.TimeField(default=datetime.datetime(2023, 6, 23, 5, 31, 59, 913628, tzinfo=datetime.timezone.utc), verbose_name='Hora de la Reserva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canchasreserva',
            name='socio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.socio'),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
