# Generated by Django 4.2.1 on 2023-06-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_remove_canchasreserva_reserva_cancha_fechacancha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='rutina',
            field=models.CharField(default='libre', max_length=1000, verbose_name='Rutina de ejercicios'),
            preserve_default=False,
        ),
    ]
