# Generated by Django 4.2.1 on 2023-05-26 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_plan_descripcionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='altura',
            field=models.IntegerField(null=True, verbose_name='Altura del Socio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='observaciones',
            field=models.CharField(max_length=500, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='peso',
            field=models.FloatField(null=True, verbose_name='Peso del Socio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='gym.plan'),
        ),
    ]
