# Generated by Django 4.2.1 on 2023-05-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_usuario_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
    ]
